### ISSUE TITLE
建议上传参数加上 ori

### ISSUE THREAD

**Issue by takashiki** [consatan/weibo_image_uploader#2]
上传接口参数中加上 `ori=1 ` 可避免高清图片被压缩，见微博图床插件：
https://github.com/Suxiaogang/WeiboPicBed/blob/master/js/background.js#L161

**Comment by takashiki** [comment]
而且用户名密码这两个参数在 Client 实例化时传入更合理吧。

**Comment by consatan** [comment]
感谢反馈，ori参数将加上（尽可能在这次更新中把其他参数也加上😅）

用户名密码之所以不在初始化时传入是为了在一个实例中任意切换账号
