### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by Hanson** [consatan/weibo_image_uploader#3]
部署服务器上发现报错，需要输入验证码，不知这种情况需要如何解决？

**Comment by consatan** [comment]
出现验证码可能是因为服务器 IP 不是常用 IP 导致的
我测试过在常用 IP 上上传图片，然后把保存的 cookie 复制到服务器上使用是可以避免出现验证码的

感觉还可以挂服务器 IP 代理，然后用网页端登入使服务器 IP 成为常用 IP，然后再部署

**Comment by Hanson** [comment]
嗯。我现在就正在服务器挂shadowsock，感觉很蛋疼

**Comment by Hanson** [comment]
我用代理也是不行。你的传cookie是怎样的？

**Comment by consatan** [comment]
我用的 cache 是本地文件，就直接把项目根目录下的 cache 文件夹复制到服务器上

**Comment by Hanson** [comment]
有点麻烦，但总算好了

http://img.hanc.cc/

这是这个项目，https://github.com/HanSon/img

我也会推广一下，顺带推广你的包 😃

**Comment by consatan** [comment]
下一步计划增加出现验证码时保存验证码图片，待手动输入验证码后保存 cookie

**Comment by Hanson** [comment]
👍 期待，今天突然想写图床，就搜了一下，就只搜到你这个包，加油

**Comment by consatan** [comment]
验证码问题已解决，cli 模式下可参考 [expamle/cli.php](https://github.com/consatan/weibo_image_uploader/blob/master/example/cli.php)
web 模式下，可直接将验证码抛给用户，让用户输入。当出现验证码时，除非提交验证码，否则所有用户看到的都是同一个验证码。

**Comment by jacena** [comment]
好像问题依旧？传了本地cookie暂时没问题，cookie过期就又不行了哦~~~
