### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by Gloduck** [consatan/weibo_image_uploader#5]
敢问验证码一直错误是怎么回事
![QQ浏览器截图20191003024916](https://user-images.githubusercontent.com/24894908/66072934-9f27a800-e588-11e9-9d51-3e76dfb36b3c.png)

**Comment by consatan** [comment]
这个上传图片的 api 已被新浪封了1个多月了，还会不会再开放就不清楚了

现在用微博图床的方法只剩下发布微博时附带图片，然后再将微博删除
